accounts/urls.py
from django.urls import path
from accounts import views as account_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

#add namespace if you want, meaning to access these paths you have to do 'accounts:<url-name>'
app_name = 'accounts'
urlpatterns = [
    path('signup/', account_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #because i use a namespace i had to put reverse url in some of the paths below. Remove them if you dont use namespace
    path('reset',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',email_template_name='accounts/password_reset_email.html',subject_template_name='accounts/password_reset_subject.txt', success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset/complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name='password_reset_complete'),
    path('myaccount/', account_views.UserUpdateView.as_view(), name='my_account'),
   
]

 
 

hms/urls.py
from django.contrib import admin
from django.urls import include,path
from hostel import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('hostel/', include('hostel.urls')),
    path('account/', include('accounts.urls')),
    path('admin/', admin.site.urls),
   
]

templates/about.html
{% extends 'master.html' %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block about_active_class %}class="active"{% endblock%}



{% block intro %}
    <div class="site-blocks-cover overlay" style="background-image: url(/static/images/hero_2.jpg)" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7 text-center" data-aos="fade">
              <h1 class="mb-4">About Us</h1>
            </div>
          </div>
        </div>
      </div>
{% endblock %} 

  {% block body %}
    <div class="site-section">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 mb-5 mb-md-0">
            
              <div class="img-border">
                <a href="https://vimeo.com/28959265" class="popup-vimeo image-play">
                  <span class="icon-wrap">
                    <span class="icon icon-play"></span>
                  </span>
                  <img src="/static/images/img_2.jpg" alt="" class="img-fluid">
                </a>
              </div>

              <!-- <img src="images/img_1.jpg" alt="Image" class="img-fluid image-absolute"> -->
            
          </div>
          <div class="col-md-5 ml-auto">
            

            <div class="section-heading text-left">
              <h2 class="mb-5">About Us</h2>
            </div>
            <p class="mb-4">Charlotte Court offers a wide range of affordable rooms to students of Ashesi University. Charlotte Court has been the awarded best hostel in Ghana for the past 4 years, and we'll continue to maintain such high standards. </p>
            <!-- <p><a href="https://vimeo.com/28959265" class="popup-vimeo text-uppercase">Watch Video <span class="icon-arrow-right small"></span></a></p> -->
          </div>
        </div>
      </div>
    </div>

    
    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Hostel Staff</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_1.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
                <h3 class="heading mb-3"><a href="#">Angella Lopez</a></h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
                <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_2.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Marina Stalks</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_3.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Ethan Hoover</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_4.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Megan Pearson</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_1.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Cristine Smith</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 mb-5">
            <div class="hotel-room text-center">
              <a href="#" class="d-block mb-4 thumbnail"><img src="/static/images/person_2.jpg" alt="Image" class="img-fluid"></a>
              <div class="p-4">
              <h3 class="heading mb-3"><a href="#">Marina Stalks</a></h3>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta labore recusandae soluta quis.</p>
              <p><a href="#" class="text-primary">Read More <span class="icon-arrow-right small"></span></a></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    


    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
            <h2 class="mb-5">Our Gallery</h2>
          </div>
        </div>
        <div class="row no-gutters">
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_1.jpg" class="image-popup img-opacity"><img src="/static/images/img_1.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_2.jpg" class="image-popup img-opacity"><img src="/static/images/img_2.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_3.jpg" class="image-popup img-opacity"><img src="/static/images/img_3.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_4.jpg" class="image-popup img-opacity"><img src="/static/images/img_4.jpg" alt="Image" class="img-fluid"></a>
          </div>
    
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_4.jpg" class="image-popup img-opacity"><img src="/static/images/img_4.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_5.jpg" class="image-popup img-opacity"><img src="/static/images/img_5.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_6.jpg" class="image-popup img-opacity"><img src="/static/images/img_6.jpg" alt="Image" class="img-fluid"></a>
          </div>
          <div class="col-md-6 col-lg-3">
            <a href="/static/images/img_7.jpg" class="image-popup img-opacity"><img src="/static/images/img_7.jpg" alt="Image" class="img-fluid"></a>
          </div>
    
        </div>
      </div>
    </div>
    
    {% endblock %}

  

templates/coming_soon.html
{% load static %}<!DOCTYPE html>
<html>
<style>
body, html {
  height: 100%;
  margin: 0;
}

.bgimg {
  background-image: url("{% static '/images/img_3.jpg' %}");
  height: 100%;
  background-position: center;
  background-size: cover;
  position: relative;
  color: white;
  font-family: "Courier New", Courier, monospace;
  font-size: 25px;
}

.topleft {
  position: absolute;
  top: 0;
  left: 16px;
}

.bottomleft {
  position: absolute;
  bottom: 0;
  left: 16px;
}

.middle {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

hr {
  margin: auto;
  width: 40%;
}
</style>
<body>

<div class="bgimg">
  <div class="topleft">
    <a style="color:white" href="{% url 'index' %}">Charlotte Court</a>
  </div>
  <div class="middle">
    <h1>COMING SOON</h1>
    <hr>
    <p id="demo" style="font-size:30px"></p>
  </div>
  <div class="bottomleft">
    <p>Stay Tuned</p>
  </div>
</div>

<script>
// Set the date we're counting down to
var countDownDate = new Date("Aug 25, 2020 15:37:25").getTime();

// Update the count down every 1 second
var countdownfunction = setInterval(function() {

  // Get todays date and time
  var now = new Date().getTime();
  
  // Find the distance between now an the count down date
  var distance = countDownDate - now;
  
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
  
  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";
  
  // If the count down is over, write some text 
  if (distance < 0) {
    clearInterval(countdownfunction);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>

</body>
</html>

templates/contact.html
{% extends 'master.html' %}
{% load static %}
{% block title %}Contact Us{% endblock %}

{% block contact_active_class %}class="active"{% endblock%}



{% block intro %}
    <div class="site-blocks-cover overlay" style="background-image: url(/static/images/hero_1.jpg);" data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7 text-center" data-aos="fade">
              <span class="caption mb-3">Chat With Us</span>
              <h1 class="mb-4">Get In Touch</h1>
            </div>
          </div>
        </div>
      </div>  
{% endblock %} 

{% block body %}
    <div class="site-section site-section-sm">
      <div class="container">
        <div class="row">
       
          <div class="col-md-12 col-lg-8 mb-5">
          
            
          
            <form action="#" class="p-5 bg-white">

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Full Name</label>
                  <input type="text" id="fullname" class="form-control" placeholder="Full Name">
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="email">Email</label>
                  <input type="email" id="email" class="form-control" placeholder="Email Address">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="phone">Phone</label>
                  <input type="text" id="phone" class="form-control" placeholder="Phone #">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <label class="font-weight-bold" for="message">Message</label> 
                  <textarea name="message" id="message" cols="30" rows="5" class="form-control" placeholder="Say hello to us"></textarea>
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Send Message" class="btn btn-primary pill px-4 py-2">
                </div>
              </div>

  
            </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">1st Avenue, Ashesi University, Berkuso</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+233 233333333</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
              <p class="mb-0"><a href="#">youremail@domain.com</a></p>

            </div>
            
            
          </div>
        </div>
      </div>
    </div>

    {% endblock %}

templates/master.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    
    <title>{% block title %}Charlotte Hostel{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700|Work+Sans:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/mediaelementplayer.min.css">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    {% block stylesheet %}{% endblock %}
    
  </head>
  <body>
  
  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    
    
    <div class="site-navbar-wrap js-site-navbar bg-white">
      <div class="container">
        <div class="site-navbar bg-light">
          <div class="py-1">
            <div class="row align-items-center">
              <div class="col-4">
                <h2 class="mb-0 site-logo"><a href="{% url 'index' %}">Charlotte Court</a></h2>
              </div>
              <div class="col-8">
                <nav class="site-navigation text-right" role="navigation">
                  <div class="container">
                    
                    <div class="d-inline-block d-lg-none  ml-md-0 mr-auto py-3"><a href="#" class="site-menu-toggle js-menu-toggle"><span class="icon-menu h3"></span></a></div>
                    <ul class="site-menu js-clone-nav d-none d-lg-block">
                      <li {% block home_active_class %}{% endblock%} >
                        <a href="{% url 'index' %}">Home</a>
                      </li>
                      <li {% block about_active_class %}{% endblock %} ><a href="{% url 'about' %}">About</a></li>
                      <li {% block rooms_active_class %}{% endblock %} ><a href="{% url 'rooms' %}">Rooms</a></li>
                      <!-- <li><a href="events.html">Events</a></li> -->
                      <li {% block contact_active_class %}{% endblock %} ><a href="{% url 'contact' %}">Contact</a></li>
                      {% if user.is_authenticated %}
                      <li class="has-children btn btn-primary pill text-white px-4">
                        <a href="#">{% firstof user.get_short_name user.get_username %}</a>
                        <ul class="dropdown arrow-top">
                          <li><a href="{% url 'dashboard' %}">My Dashboard</a></li>
                          <li><a href="{% url 'accounts:my_account' %}">My Account</a></li>
                          <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        </ul>
                      </li>
                      {% else %}
                      <li class="btn btn-primary pill text-white px-4"><a href="{% url 'accounts:login' %}">Login</a></li>
                      {% endif %}
                      <li style="display: none;"><a href="#"></a></li>
                     
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
    
    
    {% block intro %}
    {% endblock %}

    

    {% block body %}
    {% endblock %}

    
    <footer class="site-footer">
      <div class="container">
        

        <div class="row">
          <div class="col-md-4">
            <h3 class="footer-heading mb-4 text-white">About</h3>
            <p>Charlotte Court offers a wide range of affordable rooms to students of Ashesi University.</p>
            <p><a href="{% url 'about'%}" class="btn btn-primary pill text-white px-4">Read More</a></p>
          </div>
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-6">
                <h3 class="footer-heading mb-4 text-white">Quick Menu</h3>
                  <ul class="list-unstyled">
                    <li><a href="{% url 'about'%}">About</a></li>
                    <li><a href="{% url 'rooms'%}">Rooms</a></li>
                    <li><a href="{% url 'contact' %}">Contact</a></li>
                  </ul>
              </div>
              <div class="col-md-6">
                <h3 class="footer-heading mb-4 text-white">Developers</h3>
                  <ul class="list-unstyled">
                   
                  </ul>
              </div>
            </div>
          </div>

          
          <div class="col-md-2">
            <div class="col-md-12"><h3 class="footer-heading mb-4 text-white">Social Icons</h3></div>
              <div class="col-md-12">
                <p>
                  <a href="#" class="pb-2 pr-2 pl-0"><span class="icon-facebook"></span></a>
                  <a href="#" class="p-2"><span class="icon-twitter"></span></a>
                  <a href="#" class="p-2"><span class="icon-instagram"></span></a>
                  <a href="#" class="p-2"><span class="icon-vimeo"></span></a>

                </p>
              </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <p>

            Copyright &copy;<script>document.write(new Date().getFullYear());</script> Charlotte Court | All Rights Reserved

            </p>
          </div>
          
        </div>
      </div>
    </footer>
  </div>


  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-ui.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>

  
  <script src="{% static 'js/mediaelement-and-player.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>

  {% block jsfunctions %} {%endblock%}
    

  <script>
      document.addEventListener('DOMContentLoaded', function() {
                var mediaElements = document.querySelectorAll('video, audio'), total = mediaElements.length;

                for (var i = 0; i < total; i++) {
                    new MediaElementPlayer(mediaElements[i], {
                        pluginPath: 'https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/',
                        shimScriptAccess: 'always',
                        success: function () {
                            var target = document.body.querySelectorAll('.player'), targetTotal = target.length;
                            for (var j = 0; j < targetTotal; j++) {
                                target[j].style.visibility = 'visible';
                            }
                  }
                });
                }
            });
    </script>

    

  </body>
</html>

templates/payments.html
{% extends 'master.html' %}
{% load static %}
{% load humanize %}

{% block rooms_active_class %}class="active"{% endblock %}


{% block intro %}
<div class="site-blocks-cover overlay" style="background-image: url(/static/images/hero_1.jpg)" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-7 text-center" data-aos="fade">
          <h1 class="mb-2">My Payments</h1>
          <!-- <h2 class="caption">Hostel</h2> -->
        </div>
      </div>
    </div>
  </div>  
{% endblock %}

{% block body %}


<div class="site-section bg-light">
    <div class="container">
      <!-- <div class="row">
        <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          <h2 class="mb-5">Our Room Types</h2>
        </div>
      </div> -->
      <!-- <div class="row"> -->
        {% if payments %}
        <div class="table-responsive-sm">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                    <th>Room</th>
                    <th>Amount</th>
                    <th>Balance</th>
                    <th>Status</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
            {% for payment in payments %}
                    <tr>
                        <td>{{ payment.room }}</td>
                        <td>{{ payment.amount }}</td>
                        <td>{{ payment.balance }}</td>
                        <td>{{ payment.status }}</td>
                        <td>{{ payment.date_time|naturaltime }}</td>
                        {% if payment.status == 'Pending'%}
                            <td><button class="btn btn-danger">Make Payment</button></td>
                        {% elif payment.status == 'Incomplete'%}
                            <td><button class="btn btn-danger">Update Payment</button></td>
                        {% else %}
                            <td>-</td>
                        {% endif %}
                    </tr>
            {% endfor %}
            </tbody>
            </table>
            </div>
        {% else %}
        <div class="col-md-6 col-lg-3 mb-5">
            <p>No payments available</p>
        </div>
        {% endif %}
      <!-- </div> -->
    </div>
  </div>

  
  


{% endblock %}

templates/reserve_room.html
{% extends 'master.html' %}
{% load static %}
{% block title %}Room Reservation{% endblock %}

{% block intro %}
<div class="site-blocks-cover overlay" style="background-image: url(/static/images/hero_1.jpg)" data-aos="fade" data-stellar-background-ratio="0.5">
    <div class="container">
      <div class="row align-items-center justify-content-center">
        <div class="col-md-7 text-center" data-aos="fade">
          <h1 class="mb-2">Reservation</h1>
        </div>
      </div>
    </div>
  </div>  
{% endblock %}

{% block body %}
  <div class="site-section bg-light">
    <div class="container">
      <div style="margin: auto; width: 70%;" class="row">
        <div class="col-lg-12 col-md-12 col-sm-10">
          <h3>{{errors}}</h3>
            <form method="post" class="mb-4" novalidate>
                {% csrf_token %}
                {% include 'includes/form.html' %}
                {% if not errors %}
                  <button type="submit" class="btn btn-success">Reserve Room</button>
                {% endif %}

                
              </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}